### ISSUE TITLE
Error before encryption key

### ISSUE THREAD

**Issue by khanduras** [james2doyle/phileAdmin#20]
If I install and activate phileAdmin before config.php has its encryption key, the main page doesn't work.

**Comment by james2doyle** [comment]
Phile doesn't work unless you set the encryption key. It's a mandatory step.

**Comment by khanduras** [comment]
‎That's not entirely true, there's the setup page that comes first, correct? That doesn't work if encryption key is not set with phile admin activated.

**Comment by james2doyle** [comment]
If you don't set an encryption key, Phile will keep redirecting you to the setup page. That page has a link to a [generator script](https://github.com/PhileCMS/Phile/blob/master/generator.php) that will make a key for you to copy-paste. So technically Phile does still work, but it doesn't work _properly_ until the key is set. When the key is set it deletes the setup.md file and stops redirecting.

In order to create a secure username and login, that random key is needed. So phileAdmin won't work without it because it uses that key in the password encryption process.

I'm not trying to be condescending, but when [the setup instructions](https://github.com/PhileCMS/Phile/blob/master/content/setup.md) are ignored, then you post an issue about it saying things don't work, well that's on you.

**Comment by khanduras** [comment]
What I'm trying to do is create a package that comes with PhileAdmin along side it. I can make it work for what I have, it's people I give it to that might have a tough time with it. I like the setup page explaining what to do but phileAdmin causes it do display this error:

`Notice: Undefined index: class in /opt/lampp/htdocs/test_p/plugins/phile/errorHandler/Classes/Development.php on line 93`

adminPanel should be a core plugin and having it give an error before the encryption key is setup should be a faux-pas. When people download what I'm creating, I want them to copy to their directory and have a webpage tell them what to do. Right now it doesn't do that and I was wondering if that's something that can be changed or not.

**Comment by james2doyle** [comment]
Have you tried adding the encryption key to the config.json that gets created in the root folder? Also you might have to just edit the config.php or make a fork that has a auto-generating random key. 

I have been considering having the encryption key be an auto-generated dotfile instead of a key in the config, this would probably solve your problem right?

**Comment by khanduras** [comment]
Yeah that would work out!
